//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTVirtualCamera.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTVirtualCamera.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RT Virtual Camera.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Browse.
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start Preview.
        /// </summary>
        internal static string Button_StartPreview {
            get {
                return ResourceManager.GetString("Button_StartPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start VCam.
        /// </summary>
        internal static string Button_StartVCam {
            get {
                return ResourceManager.GetString("Button_StartVCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stop VCam.
        /// </summary>
        internal static string Button_StopVCam {
            get {
                return ResourceManager.GetString("Button_StopVCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Information.
        /// </summary>
        internal static string Info_Title {
            get {
                return ResourceManager.GetString("Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System.
        /// </summary>
        internal static string Language_System {
            get {
                return ResourceManager.GetString("Language_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restart the application to apply the new language..
        /// </summary>
        internal static string Language_Updated_Message {
            get {
                return ResourceManager.GetString("Language_Updated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language updated.
        /// </summary>
        internal static string Language_Updated_Title {
            get {
                return ResourceManager.GetString("Language_Updated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The selected file does not exist..
        /// </summary>
        internal static string Path_FileMissing {
            get {
                return ResourceManager.GetString("Path_FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The specified path is invalid. Use an existing local file or a valid RTSP/HTTP URL..
        /// </summary>
        internal static string Path_Invalid {
            get {
                return ResourceManager.GetString("Path_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to start preview..
        /// </summary>
        internal static string Preview_Error_Start {
            get {
                return ResourceManager.GetString("Preview_Error_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preview error.
        /// </summary>
        internal static string Preview_Error_Title {
            get {
                return ResourceManager.GetString("Preview_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preview not active.
        /// </summary>
        internal static string Preview_Inactive {
            get {
                return ResourceManager.GetString("Preview_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The source may be unreachable, slow to respond, or unsupported..
        /// </summary>
        internal static string Preview_OpenFail_Details {
            get {
                return ResourceManager.GetString("Preview_OpenFail_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The player could not open the video source..
        /// </summary>
        internal static string Preview_OpenFail_Message {
            get {
                return ResourceManager.GetString("Preview_OpenFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preview open failed.
        /// </summary>
        internal static string Preview_OpenFail_Title {
            get {
                return ResourceManager.GetString("Preview_OpenFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Possible network, decoding, or video format compatibility error..
        /// </summary>
        internal static string Preview_PlayFail_Details {
            get {
                return ResourceManager.GetString("Preview_PlayFail_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The source opened but playback did not start..
        /// </summary>
        internal static string Preview_PlayFail_Message {
            get {
                return ResourceManager.GetString("Preview_PlayFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preview start failed.
        /// </summary>
        internal static string Preview_PlayFail_Title {
            get {
                return ResourceManager.GetString("Preview_PlayFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Virtual Camera started.
        /// </summary>
        internal static string Preview_VCamStarted {
            get {
                return ResourceManager.GetString("Preview_VCamStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Media Foundation rejected opening the source..
        /// </summary>
        internal static string Probe_COM_Message {
            get {
                return ResourceManager.GetString("Probe_COM_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a InitializePlayer returned an error..
        /// </summary>
        internal static string Probe_InitFail_Details {
            get {
                return ResourceManager.GetString("Probe_InitFail_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to open the video source..
        /// </summary>
        internal static string Probe_InitFail_Message {
            get {
                return ResourceManager.GetString("Probe_InitFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GetVideoStreamInfo returned no video streams..
        /// </summary>
        internal static string Probe_NoStreams_Details {
            get {
                return ResourceManager.GetString("Probe_NoStreams_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The source opened but does not expose a usable video stream..
        /// </summary>
        internal static string Probe_NoStreams_Message {
            get {
                return ResourceManager.GetString("Probe_NoStreams_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The native component raised an internal error during probing..
        /// </summary>
        internal static string Probe_SEH_Message {
            get {
                return ResourceManager.GetString("Probe_SEH_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Probe timeout after {0} ms..
        /// </summary>
        internal static string Probe_Timeout_Details {
            get {
                return ResourceManager.GetString("Probe_Timeout_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The source did not respond in time. Check network, credentials, and stream availability..
        /// </summary>
        internal static string Probe_Timeout_Message {
            get {
                return ResourceManager.GetString("Probe_Timeout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unexpected error while checking the source..
        /// </summary>
        internal static string Probe_Unexpected_Message {
            get {
                return ResourceManager.GetString("Probe_Unexpected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Source validation failed before probing..
        /// </summary>
        internal static string Probe_Validation_Details {
            get {
                return ResourceManager.GetString("Probe_Validation_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolution:{0}x{1}@{2}.
        /// </summary>
        internal static string Resolution_Format {
            get {
                return ResourceManager.GetString("Resolution_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Source missing.
        /// </summary>
        internal static string Source_Missing_Title {
            get {
                return ResourceManager.GetString("Source_Missing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select a video file or enter a valid RTSP URL..
        /// </summary>
        internal static string Source_SelectPrompt {
            get {
                return ResourceManager.GetString("Source_SelectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Source unavailable.
        /// </summary>
        internal static string Source_Unavailable_Title {
            get {
                return ResourceManager.GetString("Source_Unavailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Technical details:.
        /// </summary>
        internal static string Tech_Details {
            get {
                return ResourceManager.GetString("Tech_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to complete the virtual camera operation..
        /// </summary>
        internal static string VirtualCamera_Error_Message {
            get {
                return ResourceManager.GetString("VirtualCamera_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Virtual camera error.
        /// </summary>
        internal static string VirtualCamera_Error_Title {
            get {
                return ResourceManager.GetString("VirtualCamera_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verify that VCamSampleSource.dll is registered, the system supports virtual cameras, and Media Foundation is available..
        /// </summary>
        internal static string VirtualCamera_RegisterFail_Details {
            get {
                return ResourceManager.GetString("VirtualCamera_RegisterFail_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Windows did not accept the virtual camera registration..
        /// </summary>
        internal static string VirtualCamera_RegisterFail_Message {
            get {
                return ResourceManager.GetString("VirtualCamera_RegisterFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Virtual camera registration failed.
        /// </summary>
        internal static string VirtualCamera_RegisterFail_Title {
            get {
                return ResourceManager.GetString("VirtualCamera_RegisterFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Possible causes: RTSP stream unavailable, negotiated format unsupported, or internal Media Foundation error..
        /// </summary>
        internal static string VirtualCamera_StartFail_Details {
            get {
                return ResourceManager.GetString("VirtualCamera_StartFail_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The virtual camera was registered but failed to start..
        /// </summary>
        internal static string VirtualCamera_StartFail_Message {
            get {
                return ResourceManager.GetString("VirtualCamera_StartFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Virtual camera start failed.
        /// </summary>
        internal static string VirtualCamera_StartFail_Title {
            get {
                return ResourceManager.GetString("VirtualCamera_StartFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Virtual Camera stopped.
        /// </summary>
        internal static string VirtualCamera_Stopped {
            get {
                return ResourceManager.GetString("VirtualCamera_Stopped", resourceCulture);
            }
        }
    }
}
